### PR TITLE
update cfc and binac genome_base and singularity version

### PR DESCRIPTION
**Pull request by KochTobi**
## Update `genome_base` and singularity version for `cfc` and `binac`
This PR aims to update the `cfc.config` and the `binac.config` to set a genome_base and `nextflow.config` to allow `cfc` and `binac` to use an `igenomes` setup.

## PR checklist
 - [x] PR is made against `dev` branch
 - [ ] PR is a hotfix against `master` branch
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Ensure the test suite passes (`./scripts/test.sh -p docker -t ALL`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/SciLifeLab/Sarek/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Looks like a nice PR.
I like the extra comments for the `conda` profile in `nexflow.config`.
Ask for me to review it and apply the ready to merge tag when you want me to review it and merge ;-).

**Comment by KochTobi** [comment]
> Looks like a nice PR.
> I like the extra comments for the `conda` profile in `nexflow.config`.
> Ask for me to review it and apply the ready to merge tag when you want me to review it and merge ;-).

Hi @MaxUlysse I don't think I can request reviews or assign labels in this repo. I just merged the dev branch into my branch. It would be great if you could review it after the tests ran through. :smiley:

**Comment by apeltzer** [comment]
I cant either, tried to do it but missing the required permissions :-(

**Comment by MaxUlysse** [comment]
It might be a good idea to promote you guys to better roles since you're developing more and more...

**Comment by apeltzer** [comment]
We promise to be humble and (trying) not to break anything ☝️

**Pull request merged**
