### PR TITLE
Use dump operator instead of our own verbose params

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Replace verbose by dump operator

## PR checklist
 - [X] PR is made against `dev` branch
 - [X] This comment contains a description of changes (with reason)
 - [X] Ensure the test suite passes (`./scripts/test.sh -p docker -t ALL`).
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by MaxUlysse** [comment]
That made a good point.
I'll change that right now.
Thanks for the idea

**Comment by MaxUlysse** [comment]
@szilvajuhos What do you think of this option: https://github.com/SciLifeLab/Sarek/pull/741/files#diff-0b5797602b3120dfd4f9caa8ea5c8a9eR236 ?

**Comment by szilvajuhos** [comment]
Writing out the new option is OK, especially for this. On the other hand, we should avoid changing the CLI.

**Comment by MaxUlysse** [comment]
I know we should avoid changing it, unless we go for 2.4 ;-)

But I do think it'll be better to have this dump operator than what we were doing before.

**Comment by MaxUlysse** [comment]
next version will be `2.4` since this PR is breaking `--verbose`

**Comment by apeltzer** [comment]
Can help you with reviewing and testing here to get a 2.4 release soon :)

**Comment by MaxUlysse** [comment]
I'm currently testing #773 #787 
#781 could need further testing, and some files added in iGenomes
And I definitively need #781 in `2.4`
It would be great if we can have #789 as well
#790 will also need to be included, but no testing required

**Pull request merged**
