### PR TITLE
one Conda environment to rule them all

### PR DESCRIPTION
**Pull request by MaxUlysse**
- Remove `GetVersionAlleleCount` and `GetVersionASCAT` processes
- Remove `r-base` and `runallelecount` containers
- Install `cancertit-allelecount 2.1.2` with Bioconda
- Install `RColorBrewer 1.1` with Conda
- Install `Bioconductor-Rtracklayer 1.42.1` with Bioconda
- Update `BCFTools` from `1.8` to `1.9`
- Update `GATK4` from `4.0.9.0` to `4.1.0.0`
- Update `Manta` from `1.4.0` to `1.5.0`
- Update `samtools` from `1.8` to `1.9`
- Update `Strelka` from `2.9.3` to `2.9.10`
- Update `VCFanno` from `0.3.0` to `0.3.1`
- Update `VEP` cache from `95` to `96`
- Update `VEP` version from `95.2` to `96.0`

## PR checklist
 - [X] PR is made against `dev` branch
 - [X] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [X] Ensure the test suite passes (`./scripts/test.sh -p docker -t ALL`).
 - [X] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by MaxUlysse** [comment]
Obviously failing because VEP is requesting cache and software version 96, and the container is currently only in 95.
Need to update at least allelecount in bioconda before continuing on that updating of all tools.

**Comment by apeltzer** [comment]
Started working on alleleCount: https://github.com/bioconda/bioconda-recipes/pull/14740

**Comment by MaxUlysse** [comment]
Thanks, I tried doing it, but I'm definitively not as efficient.
Can you add `2.2.0` as well, so that we can start with the same version we're currently using?

**Comment by apeltzer** [comment]
`cancerit-allelecount=4.0.2` is now on bioconda. https://anaconda.org/bioconda/cancerit-allelecount/files

**Pull request merged**
